# Generated by Django 4.1.7 on 2023-02-18 06:04

import detector.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detector", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userimages",
            name="img",
            field=models.ImageField(
                null=True, upload_to=detector.models.generate_filename
            ),
        ),
    ]
